table dim_date
	lineageTag: a764fb40-580c-4a8b-aa29-43ecb051efbf

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 60a0ec83-b273-4a64-a7bb-5b3ecfc7b489
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e679f85f-54b3-412b-8f6c-eeda16772fb2
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 18681bd1-df42-4e53-aee8-04553279e89b
			defaultHierarchy: LocalDateTable_a770d693-9d56-4f7c-9ed6-6b36f9c6e9d3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: f6408d62-b4a9-47db-b51d-6b11c5570fc3
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: debb1aeb-f523-444c-8e38-25c5ccb911b8
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 987b0339-b71a-437e-b48f-dda2236cb9cc
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 9c5c4e7c-4d56-4a07-b7d2-68d14a594bf8
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column week
		dataType: int64
		formatString: 0
		lineageTag: 81fa868c-6949-44c6-a0c8-8ba63656f9dc
		summarizeBy: sum
		sourceColumn: week

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: d14d989d-a174-4ff2-b9ee-3393f0cb6d97
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 54bb24ae-4e4f-461a-a72d-84ac1f61099a
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 1b2a171e-a356-4f6d-a4f5-549ad23147e7
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 26bdb4bc-12e9-4fd0-819c-fdfbb10ef476
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column Month_Short = FORMAT(dim_date[date], "MMM")
		lineageTag: 242ff3ff-e3d4-4310-ae10-b1a0a832a905
		summarizeBy: none
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Folder,
				    #"C:\Users\Acer\Downloads\Dataset\_dim_date csv" = Source{[#"Folder Path"="C:\Users\Acer\Downloads\Dataset\",Name="dim_date.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\Acer\Downloads\Dataset\_dim_date csv",[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"week", Int64.Type}, {"day", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

